### PR TITLE
Web App Development

### PR DESCRIPTION
**Pull request by MolefeSentshopac**

### CODE REVIEW

**Comment by MolefeSentshopac** [comment]
Yes it’s a mistake I rectified sorry

**Comment by MolefeSentshopac** [comment]
Stupit mistake my apologies

**Comment by MolefeSentshopac** [comment]
Greetings mam

Mam we have a database problem i am done with the project i want to submit,
this project is important to me to see i am looking forward to good marks
here and this database problem is worrying me

regards

**Comment by MolefeSentshopac** [comment]
hello mam

i created my own database on azure and my API works so hopefully thats okay

**Comment by JacquiM** [comment]
I am unable to see what the problem is

**Comment by MolefeSentshopac** [comment]
Greetings mam

Mam I just finished my GitHub now because of loadshedding hope I won’t get
paralysed sorry

Thank you

**Comment by MolefeSentshopac** [comment]
Mam I would like to query the project 4 mam I asked you nicely because of
loadshedding I submitted the wrong one please mam

**Comment by MolefeSentshopac** [comment]
That’s the correct URL I submitted please mam have mercy on me Loadshedding
disrupted my submission 😭😭🙏🙏
There is the email

**Comment by MolefeSentshopac** [comment]
I sent the email just after the lights came back on during the submission
day minutes after submission 😭😭😭please

**Comment by MolefeSentshopac** [comment]
I deserve to not get a mark for no test result submitted because I remember
I didn’t submit them because I was in a rush but the rest I did send you
the URL on email because I submitted the wrong one I did say mam

**Comment by MolefeSentshopac** [comment]
Mam my initial commit for project 5 was on 24 September so it is well under
7 days I didn’t get a mark for that 😭😭

Also my reference list is 26 I also didn’t get a mark for that part 😭
My board was updated and I also spent 11 hours and more on the board also
no marks

**Comment by MolefeSentshopac** [comment]
But mam why arnt you replying 😭😭

**Pull request closed without merging**
